# Generated by Django 3.1.5 on 2021-01-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('despation', models.CharField(max_length=500)),
                ('year', models.IntegerField(default=0)),
                ('image', models.ImageField(max_length=1000, upload_to=None)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
